package com.lontongmalam.clubsinbundesliga2020

object ClubData {
    private val itemId = intArrayOf(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17)

    private val clubNames = arrayOf(
            "FC Augsburg",
            "Hertha BSC",
            "Union Berlin",
            "Arminia Bielefeld",
            "Werder Bremen",
            "Borussia Dortmund",
            "Eintracht Frankfurt",
            "SC Freiburg",
            "1899 Hoffenheim",
            "FC Köln",
            "RB Leipzig",
            "Bayer Leverkusen",
            "Mainz 05",
            "Borussia Mönchengladbach",
            "Bayern Munich",
            "Schalke 04",
            "VfB Stuttgart",
            "VfL Wolfsburg")

    private val clubDescs = arrayOf(
            "Fußball-Club Augsburg 1907 e. V., commonly known as FC Augsburg (German pronunciation: [ʔɛf tseː ˈʔaʊksbʊʁk]) or Augsburg, is a German football club based in Augsburg, Bavaria. FC Augsburg play in the Bundesliga, the top tier of the German football league system. The team was founded as Fußball-Klub Alemania Augsburg in 1907 and played as BC Augsburg from 1921 to 1969. With over 18,800 members, it is the largest football club in Swabian Bavaria.\n\nThe club has spent most of its history fluctuating between the second and third divisions, with disappointment striking in the early 2000s when Augsburg were relegated to the fourth division for two seasons. However, the club experienced a surge following this setback, and was eventually promoted to the Bundesliga for the first time in 2011, where it has remained ever since. Augsburg have consolidated their Bundesliga status in the 2010s, finishing a record high fifth in the 2014–15 season before several mid-table finishes, and made their European debut in the 2015–16 UEFA Europa League, with the club reaching the Round of 32 before being knocked out by Liverpool 1–0 on aggregate.\n\nSince 2009, FC Augsburg's stadium has been the 30,660 capacity WWK ARENA, located south of Augsburg city centre and easily accessible via tram. The club, known as the Fuggerstädter or simply as FCA, receive strong home support with an average attendance of 28,709 in the 2019–20 Bundesliga season (93.6% of stadium capacity). It is a single tier stadium with a standing terrace behind one of the goals, known as the Ulrich-Biesinger-Tribüne, and three seated stands with a standing section in the opposite corner to the Ulrich-Biesinger-Tribüne for away fans.",
            "Hertha, Berliner Sport-Club e. V., commonly known as Hertha BSC (German pronunciation: [ˈhɛʁtaː beː ʔɛs t͡seː]), and sometimes referred to as Hertha Berlin, Hertha BSC Berlin, or simply Hertha, is a German professional football club based in the Charlottenburg locality of Berlin. Hertha BSC plays in the Bundesliga, the top tier of German football. Hertha BSC was founded in 1892, and was a founding member of the German Football Association in Leipzig in 1900.\n\nThe team won the German championship in 1930 and 1931. Since 1963, Hertha's stadium has been the Olympiastadion. The club is known as Die Alte Dame in German, which translates to \"The Old Lady\". In 2002, the sports activities of the professional, amateur, and under-19 teams were separated into Hertha BSC GmbH & Co. KGaA.",
            "U1. Fußballclub Union Berlin e. V., commonly known as 1. FC Union Berlin (German pronunciation: [ˈʔeːɐ̯s.tɐ ʔɛf tseː ʊnˈɪ̯oːn bɛɐ̯ˈliːn]) or simply Union Berlin, is a professional German association football club based in Köpenick, Berlin. The club emerged under the current name in 1966 but its origins can be traced back to 1906, when its predecessor FC Olympia Oberschöneweide was founded. From 2009 until 2019, they competed in the 2. Bundesliga, the second tier of German football. In 2019, after defeating VfB Stuttgart in the relegation play-offs, Union won promotion to the Bundesliga top flight for the first time in the club's history, for the 2019–20 season.\n\nDuring the Cold War era, Union was based in the East Berlin sector of the city, joining the common German league structure upon the reunification of the city and the country in 1990.\n\nThe home ground Stadion An der Alten Försterei (Stadium by the Old Forester's House) is the largest single-purpose football stadium in the German capital. It has been home to Union Berlin and its forerunners since it was opened in 1920. The stadium became internationally famous for concerts and events like the annual Weihnachtssingen (Christmas Carols Event) and the WM-Wohnzimmer (World Cup Living Room) in 2014.\n\nThe club has become well known for its enthusiastic and creative fan base and for its chant \"Eisern Union\" (Iron Union).",
            "DSC Arminia Bielefeld (pronounced [ˌdeːʔɛsˈtseː ʔaʁˈmiːni̯a ˈbiːləfɛlt]; full name: Deutscher Sportclub Arminia Bielefeld e.V. [ˈdɔʏtʃɐ ˈʃpɔʁtklʊp ʔaʁˈmiːni̯a ˈbiːləfɛlt]; also known as Die Arminen [diː ˈʔaʁmiːnən] or Die Blauen [diː ˈblaʊən]), or just Arminia, is a German sports club from Bielefeld, North Rhine-Westphalia. Arminia offers the sports of football, field hockey, figure skating and cue sports. The club has 12,000 members and the club colours are black, white and blue. Arminia's name derives from the Cheruscan chieftain Arminius, who defeated a Roman army in the Battle of the Teutoburg Forest.\n\nThe club is most commonly known for its professional football team that play in the Bundesliga and mostly played in the first or second tier of the German football league system, among them 17 seasons in the 1. Bundesliga, to which they have recently returned. Arminia's most successful years were the 1920s, the early 1980s and the middle 2000s. In 1947 and in the 1950s Arminia had sunk down to a team playing in a rather local area in the third tier (later third tiers covered larger areas).\n\nArminia has been playing their home games at the Bielefelder Alm Stadium since 1926. Since 2004 the stadium has been named SchücoArena through a sponsorship deal.",
            "Sportverein Werder Bremen von 1899 e. V. (German pronunciation: [ˈvɛɐ̯dɐ ˈbʁeːmən]), commonly known as Werder Bremen, Werder or simply Bremen, is a German professional sports club based in Bremen, Free Hanseatic City of Bremen. Founded on 4 February 1899, they are best known for their professional football team, who will be competing in the 2. Bundesliga, the second tier of the German football league system, as of the 2021–22 season. Werder hold the record for most seasons played in the Bundesliga and are third in the all-time Bundesliga table, behind Bayern Munich and Borussia Dortmund.\n\nWerder have been German champions four times, have won the DFB-Pokal six times, the DFL-Ligapokal once, the DFL-Supercup thrice, and the European Cup Winners' Cup once. The team's first major trophy came in the 1960–61 DFB-Pokal, a competition they last won in 2008–09. Their first German championship came in 1964–65, and their latest in 2003–04, when they won the double. In Europe, Werder won the 1992 European Cup Winners' Cup in a final against AS Monaco. They were runners-up in the 2008–09 UEFA Cup, losing against Shakhtar Donetsk in the final.\n\nSince 1909, Werder have played at the Weserstadion. The team have a rivalry with fellow northern German club Hamburger SV, known as the Nordderby (English: North derby). In November 2019, Werder had 40,376 members.",
            "Ballspielverein Borussia 09 e. V. Dortmund, commonly known as Borussia Dortmund [boˈʁʊsi̯aː ˈdɔɐ̯tmʊnt], BVB, or simply Dortmund, is a German professional sports club based in Dortmund, North Rhine-Westphalia. It is best known for its men's professional football team, which plays in the Bundesliga, the top tier of the German football league system. The club have won eight league championships, five DFB-Pokals, one UEFA Champions League, one Intercontinental Cup, and one UEFA Cup Winners' Cup.\n\nFounded in 1909 by eighteen football players from Dortmund, the football team is part of a large membership-based sports club with more than 145,000 members, making Borussia Dortmund the second largest sports club by membership in Germany. The club has active departments in other sports, namely in women's handball. Since 1974, Dortmund have played their home games at Westfalenstadion; the stadium is the largest in Germany, and Dortmund has the highest average attendance of any association football club in the world.\n\nBorussia Dortmund's colours are black and yellow, giving the club its nickname die Schwarzgelben. They hold a long-standing rivalry with Ruhr neighbours Schalke 04, with whom they contest the Revierderby. They also contest Der Klassiker with Bayern Munich.\n\nIn terms of Deloitte's annual Football Money League, Dortmund was in 2015 ranked as the second richest sports club in Germany, and the 12th richest football team in the world. Moreover, under the directorship of Michael Zorc in the 2010s, Dortmund have cultivated a reputation for spotting and developing young talent, and have remained focused on developing a youth system. They have also received plaudits for generally adhering to an attacking footballing philosophy.",
            "Eintracht Frankfurt e.V. (German pronunciation: [ˈʔaɪntʁaxt ˈfʁaŋkfʊʁt]) is a German professional sports club based in Frankfurt, Hesse, that is best known for its football club, currently playing in the Bundesliga, the top tier of the German football league system. The club was founded in 1899 and have won one German championship, five DFB-Pokals, one UEFA Cup and once finished as runner-up in the European Cup. The team was one of the founding members of the Bundesliga at its inception and has spent a total of 51 seasons in the top division, thus making them the seventh longest participating club in the highest tier of the league.\n\nThe club's first matches from 1899 to 1906 were played on the former Hundswiese field, whose present day location would be near Hessischer Rundfunk. Following new regulations that pitches needed to be surrounded by a fence for the purpose of official games, the team established a new pitch by the Eschersheimer Landstraße called Victoriaplatz in 1906, for which they purchased stands at a price of 350 marks in 1908. From 1912 the team moved to a new ground at Roseggerstraße in Dornbusch with more facilities, before relocating to the former Riederwaldstadion in 1920 following the fusion of Frankfurter FV and Frankfurter Turngemeinde von 1861. Since 1925 their stadium has been the Waldstadion, which was renamed Deutsche Bank Park for sponsorship reasons.\n\nEintracht Frankfurt have enjoyed some success in the Bundesliga, having either won or drawn more than three-quarters of their games as well as having finished the majority of their seasons placed in the top half of the table, but also having the highest number of losses in the league (657). With an average attendance of 47,942 since 2013 the team also boasts one of the highest attendance ratings in the world and the eighth highest out of the 36 Bundesliga and 2. Bundesliga teams. The player with the highest number of appearances (602) in the Bundesliga, Charly Körbel, spent his entire senior career as a defender for Eintracht Frankfurt. The club's primary rival is local club Kickers Offenbach, although due to spending most of their history in different divisions, the two have only played two league matches within the last 40 years.",
            "Sport-Club Freiburg e.V., commonly known as SC Freiburg (German pronunciation: [ʔɛs ˈtseː ˈfʁaɪbʊɐ̯k]), is a German football club, based in the city of Freiburg im Breisgau, Baden-Württemberg. It plays in the Bundesliga, having been promoted as champions from the 2. Bundesliga in 2016. Freiburg has traditionally bounced between the first and second tier of the German football league system, leading to the fan chant, \"We go down, we go up, we go into the UEFA Cup!\" during the 1990s.\n\nSince 1954, the club's stadium has been the Schwarzwald-Stadion. The club is set to move to the newly built SC-Stadion in 2021. Volker Finke, who was the club's manager between 1991 and 2007, was the longest-serving manager in the history of professional football in Germany. Joachim Löw, current manager of the Germany national team, is the club's second highest all-time leading goal scorer with 81 goals in 252 games during his three spells at the club, behind Nils Petersen.",
            "Turn- und Sportgemeinschaft 1899 Hoffenheim e.V., or simply TSG 1899 Hoffenheim or just Hoffenheim (pronounced [teː ʔɛs ɡeː ˈʔaxt͡seːnˈhʊndɐt ˈnɔʏ̯nʔʊntˈnɔʏ̯nt͡sɪç ˈhɔfn̩haɪ̯m]) is a German professional football club based in Hoffenheim, a village of Sinsheim municipality, Baden-Württemberg.\n\nOriginally founded in 1899 as a gymnastics club, Hoffenheim came into being in its modern form in 1945. A fifth division side in 2000, the club rapidly advanced through the German football league system with the financial backing of alumnus and software mogul Dietmar Hopp, and in 2008 Hoffenheim was promoted to the top tier Bundesliga. In the 2017–18 season, Hoffenheim finished third in the Bundesliga (its best to date), qualifying for the UEFA Champions League group stage for the first time.\n\nSince 2009, Hoffenheim has played its home games at the Rhein-Neckar-Arena (currently known as PreZero Arena), having previously played at the Dietmar-Hopp-Stadion from 1999.",
            "1. Fußball-Club Köln 01/07 e. V., commonly known as simply FC Köln or FC Cologne in English (German pronunciation: [ʔɛf ˈtseː ˈkœln]), is a German professional football club based in Cologne in North Rhine-Westphalia. It was formed in 1948 as a merger of the clubs Kölner Ballspiel-Club 1901 and SpVgg Sülz 07. Köln competes in the Bundesliga after promotion in 2018–19 following relegation to 2. Bundesliga the previous season. The team are two-time top-flight champions, winning the Bundesliga in 1964 and 1978. The team plays its home matches at Rheinenergiestadion.\n\nThe club's nickname Die Geißböcke (The Billy Goats) refers to the club's mascot, a male goat named Hennes after the veteran FC player and later manager Hennes Weisweiler. The first Hennes was donated by a circus entrepreneur as a Cologne carnival joke. The current mascot is Hennes IX as of 1 August 2019 after Hennes VIII was retired by the club due to old age. Another nickname for the club, more common locally due to its ambiguity, is FC (often written as Effzeh), a common German abbreviation for football clubs. Characteristic for the dialect spoken around Cologne, this is pronounced \"EF-tsay\", in contrast to the Standard German pronunciation of the abbreviation where the second syllable is emphasized ([ʔɛf ˈtseː]). Köln play at home in white and red, both colours having been used as the main shirt colour throughout its history. The club has long-standing rivalries with nearby clubs Borussia Mönchengladbach, Fortuna Düsseldorf, and Bayer Leverkusen.\n\nLike many of Germany's other professional football clubs, 1. FC Köln is part of a larger sports club with teams in other sports like handball, table tennis and gymnastics. 1. FC Köln has over 100,000 members, making it the fourth largest club in Germany.",
            "RasenBallsport Leipzig e.V. (lit. 'Lawn Ball Sports Leipzig'), commonly known as RB Leipzig or informally as Red Bull Leipzig, is a German professional football club based in Leipzig, Saxony. The club was founded in 2009 by the initiative of the company Red Bull GmbH, which purchased the playing rights of fifth-tier side SSV Markranstädt with the intent of advancing the new club to the top-flight Bundesliga within eight years. The men's professional football club is run by the spin-off organization RasenBallsport Leipzig GmbH. RB Leipzig plays its home matches at the Red Bull Arena.\n\nIn its inaugural season in 2009–10, RB Leipzig dominated the NOFV-Oberliga Süd (V) and was promoted as champions to the Regionalliga Nord (IV). RB Leipzig won the 2012–13 Regionalliga Nordost season without a single defeat and was promoted to the 3. Liga (III), then finished the 2013–14 3. Liga season as runners-up and was promoted to the 2. Bundesliga (II) as the first team since the introduction of the 3. Liga to win promotion after only one season.\n\nOn 8 May 2016, RB Leipzig ensured promotion to the Bundesliga for the 2016–17 season with a 2–0 win over Karlsruher SC. One year later, RB Leipzig captured a place in the 2017–18 UEFA Champions League by finishing as runners-up in the Bundesliga. On 18 August 2020, the club made history by participating in their first Champions League semi-finals, losing against Paris Saint-Germain of France.\n\nThe club nickname is Die Roten Bullen (English: The Red Bulls) due to the energy drink company Red Bull being the sole investor of the club.",
            "Bayer 04 Leverkusen Fußball GmbH, also known as Bayer 04 Leverkusen (German: [ˌbaɪ̯ɐ ˈleːvɐˌkuːzn̩]), Bayer Leverkusen, or simply Leverkusen, is a German professional football club based in Leverkusen in the state of North Rhine-Westphalia. The club competes in the Bundesliga, the top tier of German football, and plays its home matches at the BayArena.\n\nThe club was founded in 1904 by employees of the German pharmaceutical company Bayer AG, whose headquarters are in Leverkusen and from which the club draws its name. It was formerly the best-known department of TSV Bayer 04 Leverkusen, a sports club whose members also participate in athletics, gymnastics, basketball and other sports including the RTHC Bayer Leverkusen (rowing, tennis and hockey). In 1999 the football department was separated from the sports club and is now a separate entity formally called Bayer 04 Leverkusen GmbH. Bayer were first promoted to the Bundesliga in 1979, and have remained in the top division ever since. The club's main colours are red and black, both having been used as the main shirt colour and with red and black stripes also having been used as home colours.\n\nBayer Leverkusen have finished five times runner-up in the Bundesliga without winning the competition, a record in German football. The club has won one DFB-Pokal and one UEFA Cup. Bayer also finished runner-up in the 2001–02 UEFA Champions League, falling 2–1 to Real Madrid in the final. Their local rivals are 1. FC Köln.",
            "1. Fußball- und Sportverein Mainz 05 e. V., usually shortened to 1. FSV Mainz 05, Mainz 05 [ˌmaɪnts nʊlˈfʏnf] or simply Mainz, is a German sports club, founded in 1905 and based in Mainz, Rhineland-Palatinate. 1. FSV Mainz 05 have played in the Bundesliga, the top tier of the German football league system, for ten consecutive years, starting with the 2009–10 season. The club's main local rivals are Eintracht Frankfurt and 1. FC Kaiserslautern. In addition to the football division, 1. FSV Mainz 05 have handball and table tennis departments.",
            "Borussia Verein für Leibesübungen 1900 e. V. Mönchengladbach, commonly known as Borussia Mönchengladbach (pronounced [boˈʁʊsi̯aː mœnçn̩ˈɡlatbax]), Mönchengladbach or Gladbach (abbreviated as Borussia MG), is a professional football club based in Mönchengladbach, North Rhine-Westphalia, Germany, that plays in the Bundesliga, the top flight of German football. The club has won five League titles, three DFB-Pokals, and two UEFA Europa League titles.\n\nBorussia Mönchengladbach were founded in 1900, with its name derived from a Latinized form of Prussia, which was a popular name for German clubs in the former Kingdom of Prussia. The team joined the Bundesliga in 1965, and saw the majority of its success in the 1970s, where, under the guidance of Hennes Weisweiler and then Udo Lattek, they captured five league championships with Die Fohlen [diː ˈfoːlən] (The Colts) team; a term coined as the squad were young with a fast, aggressive playing style. Mönchengladbach also won two UEFA Cup titles during this period and reached a European Cup final in 1977.\n\nSince 2004, Borussia Mönchengladbach have played at Borussia-Park, having previously played at the Bökelbergstadion since 1919. Based on membership, Borussia Mönchengladbach is the fifth largest club in Germany with over 75,000 members in 2016, and 93,000 members as of 2021. The club's main rivals are FC Köln, against whom they contest the Rheinland Derby. Their secondary rivals include Borussia Dortmund, Fortuna Düsseldorf, and Bayer Leverkusen.",
            "Fußball-Club Bayern München e. V. (German pronunciation: [ˈfuːsbalˌklʊp ˈbaɪɐn ˈmʏnçn̩]), commonly known as FC Bayern München (German pronunciation: [ʔɛf tseː ˈbaɪɐn ˈmʏnçn̩]), FCB, Bayern Munich, or FC Bayern, is a German professional sports club based in Munich, Bavaria. It is best known for its professional football team, which plays in the Bundesliga, the top tier of the German football league system. Bayern is the most successful club in German football history, having won a record 31 national titles, including nine consecutively since 2013, and 20 national cups, along with numerous European honours.\n\nFC Bayern Munich was founded in 1900 by 11 football players, led by Franz John. Although Bayern won its first national championship in 1932, the club was not selected for the Bundesliga at its inception in 1963. The club had its period of greatest success in the mid-1970s when, under the captaincy of Franz Beckenbauer, it won the European Cup three consecutive times (1974–1976). Overall, Bayern has reached eleven European Cup/UEFA Champions League finals, winning their sixth title in the 2020 final as part of a continental treble, after which it became only the second European club to achieve the continental treble twice. Bayern has also won one UEFA Cup, one European Cup Winners' Cup, two UEFA Super Cups, two FIFA Club World Cups and two Intercontinental Cups, making it one of the most successful European clubs internationally and the only German club to have won both international titles. By winning the 2020 FIFA Club World Cup, Bayern Munich became only the second club to win the sextuple. Bayern Munich are one of five clubs to have won all three of UEFA's main club competitions, the only German club to achieve the UEFA treble. As of May 2021, Bayern Munich are ranked first in UEFA club rankings. The club has traditional local rivalries with 1860 Munich and 1. FC Nürnberg, as well as with Borussia Dortmund since the mid-1990s.\n\nSince the beginning of the 2005–06 season, Bayern has played its home games at the Allianz Arena. Previously the team had played at Munich's Olympiastadion for 33 years. The team colours are red and white, and the crest shows the white and blue flag of Bavaria. In terms of revenue, Bayern Munich is the largest sports club in Germany and the third highest-earning football club in the world, generating €634.1 million in 2021. In November 2019, Bayern had 293,000 official members and 4,499 officially registered fan clubs with over 350,000 members. The club has other departments for chess, handball, basketball, gymnastics, bowling, table tennis and senior football with more than 1,100 active members.",
            "Fußballclub Gelsenkirchen-Schalke 04 e. V., commonly known as FC Schalke 04 (German: [ɛf tseː ˈʃalkə nʊl fiːɐ̯]), Schalke 04, or abbreviated as S04 (German: [ˈɛs nʊl fiːɐ̯]), is a professional German football and multi-sports club originally from the Schalke district of Gelsenkirchen, North Rhine-Westphalia. The \"04\" in the club's name derives from its formation in 1904. Schalke has long been one of the most popular professional football teams and multi-sports club in Germany, even though the club's heyday was in the 1930s and 1940s. Schalke play in the 2. Bundesliga, the second tier of the German football league system, as a result of the 2020–21 relegation. As of June 2018, the club has 155,000 members, making it the second-largest sports club in Germany and the fourth-largest sports club in the world in terms of membership.[not verified in body] Other activities offered by the club include athletics, basketball, handball, table tennis, winter sports and eSports.\n\nFounded in 1904, Schalke has won seven German championships, five DFB-Pokals, one DFL-Supercup and one UEFA Cup. Schalke also succeeded as the first German club to win a cup double in 1937.\n\nSince 2001, Schalke's stadium has been the Veltins-Arena. Schalke holds a long-standing rivalry with Ruhr neighbours Borussia Dortmund, arguably one of the most widespread and well-known rivalries in German football, and matches between the two teams are referred to as the Revierderby.\n\nSchalke was ranked as the 31st-best football team in Europe by UEFA's 2020 UEFA club rankings, and ranked 7th-best in 2015 UEFA club rankings.\n\nIn terms of operating income, Schalke possesses the seventh-highest of any football club at \$64.4 million or £38.2 million (€48 million), and 0 per cent debt as of August 2014. Schalke also generates the 14th-highest revenue of any football club, at \"\$265.6 million or £157.8 million (€198 million)\".\n\nIn May 2014, Schalke 04 were ranked by Forbes magazine as the 14th-most valuable football club, at \"£355 million or \$599 million (€446 million)\", an increase of 16 per cent from the previous year.",
            "Verein für Bewegungsspiele Stuttgart 1893 e. V., commonly known as VfB Stuttgart (German pronunciation: [faʊ̯ ʔɛf beː ˈʃtʊtɡaʁt]), is a German sports club based in Stuttgart, Baden-Württemberg. The club's football team is currently part of Germany's first division, the Bundesliga. VfB Stuttgart is one of Germany's most successful clubs. The club has won the national championship five times, most recently in 2006–07, the DFB-Pokal three times and the UEFA Intertoto Cup a record three times.\n\nThe football team plays its home games at the Mercedes-Benz Arena, in the Neckarpark which is located near the Cannstatter Wasen, where the city's fall beer festival takes place. Second team side VfB Stuttgart II currently plays in the Regionalliga Südwest, which is the second highest division allowed for a reserve team. The club's junior teams have won the national U19 championships a record ten times and the Under 17 Bundesliga six times.\n\nA membership-based club with over 64,000 members, VfB is the largest sports club in Baden-Württemberg and the fifth-largest in Germany. It has departments for fistball, field hockey, track and field, table tennis, and football referees, all of which compete only at the amateur level. The club also maintains a social department, the VfB-Garde.",
            "Verein für Leibesübungen Wolfsburg e. V., commonly known as VfL Wolfsburg (pronounced [ˌfaʊ ʔɛf ʔɛl ˈvɔlfsbʊɐ̯k]) or Wolfsburg, is a German professional sports club based in Wolfsburg, Lower Saxony. The club grew out of a multi-sports club for Volkswagen workers in the city of Wolfsburg. It is best known for its football department, but other departments include badminton, handball and athletics.\n\nThe men's professional football team play in the Bundesliga, the top tier of the German football league system. Wolfsburg have won the Bundesliga once in their history, in the 2008–09 season, the DFB-Pokal in 2015 and the DFL-Supercup in 2015.\n\nProfessional football is run by the spin-off organization VfL Wolfsburg-Fußball GmbH, a wholly owned subsidiary of the Volkswagen Group.[2][3] Since 2002, Wolfsburg's stadium is the Volkswagen Arena.")

    private val clubLogos = intArrayOf(
            R.drawable.club_1_logo,
            R.drawable.club_2_logo,
            R.drawable.club_3_logo,
            R.drawable.club_4_logo,
            R.drawable.club_5_logo,
            R.drawable.club_6_logo,
            R.drawable.club_7_logo,
            R.drawable.club_8_logo,
            R.drawable.club_9_logo,
            R.drawable.club_10_logo,
            R.drawable.club_11_logo,
            R.drawable.club_12_logo,
            R.drawable.club_13_logo,
            R.drawable.club_14_logo,
            R.drawable.club_15_logo,
            R.drawable.club_16_logo,
            R.drawable.club_17_logo,
            R.drawable.club_18_logo)

    private val stadNames = arrayOf(
            "WWK Arena",
            "Olympiastadion",
            "Stadion An der Alten Försterei",
            "Schüco-Arena",
            "Wohninvest Weserstadion",
            "Signal Iduna Park",
            "Deutsche Bank Park",
            "Schwarzwald-Stadion",
            "PreZero Arena",
            "RheinEnergieStadion",
            "Red Bull Arena",
            "BayArena",
            "Opel Arena",
            "Borussia-Park",
            "Allianz Arena",
            "Veltins-Arena",
            "Mercedes-Benz Arena",
            "Volkswagen Arena")

    private val stadDescs = arrayOf(
            "Augsburg Arena, currently known commercially as the WWK Arena (German pronunciation: [ˌveːveːˈkaː ʔaˌʁeːna], officially stylised as WWK ARENA) is a football stadium in Augsburg, Bavaria, Germany. It is used mostly for football matches and hosts the home matches of FC Augsburg.\n\nThe stadium has a capacity of 30,660 with 19,060 seats and standing room for 11,034. A second phase of construction could expand capacity to 49,000 in the future. It replaced the club's previous home stadium, Rosenaustadion. FC Augsburg played their first match in the new stadium in 2009",
            "The Olympiastadion (German pronunciation: [oˈlʏmpi̯aˌʃtaːdi̯ɔn]) is a sports stadium at Olympiapark Berlin in Berlin, Germany. It was originally built by Werner March for the 1936 Summer Olympics. During the Olympics, the record attendance was thought to be over 100,000. Today the stadium is part of the Olympiapark Berlin.\n\nSince renovations in 2004, the Olympiastadion has a permanent capacity of 74,475 seats and is the largest stadium in Germany for international football matches. The Olympiastadion is a UEFA category four stadium and one of the world's most prestigious venues for sporting and entertainment events.",
            "Stadion An der Alten Försterei (English: Stadium at the old forester's house) is a football stadium in Köpenick and the largest single-purpose football stadium in the German capital of Berlin. It has been home to football club 1. FC Union Berlin and its forerunners since its opening in 1920.\n\nThe stadium's capacity was last redeveloped in 2009 and expanded in 2013. Some of the redevelopment work was carried out by over 2,300 Union Berlin supporters volunteering their services. During league matches the arena features a total capacity of 22,012. There are 3,617 seats available whilst the rest of the ground remains terracing.\n\nThe stadium became also known for events like the annual \"Weihnachtssingen\" (Christmas Carols Event) and the \"WM-Wohnzimmer\" (World Cup Living Room) in 2014.",
            "Bielefelder Alm (German pronunciation: [ˈbiːləfɛldɐ ˈʔalm]) is a football stadium in Bielefeld, Germany. The stadium, which has a capacity of 26 515, is owned by the football club DSC Arminia Bielefeld and mostly used for the club's matches. Formerly named Stadion Alm [ˈʃtaːdi̯ɔn ˈʔalm], it is currently known as SchücoArena [ˈʃyːkoːʔaˈʁeːnaː] due to a sponsorship deal with the Bielefeld-based window and solar panel manufacturers.",
            "Weserstadion (German pronunciation: [ˈveːzɐˌʃtaːdi̯ɔn]) is a multi-purpose stadium in Bremen, Germany. The Weserstadion is scenically situated on the north bank of the Weser River and is surrounded by lush green parks (the name 'Werder' is a regional German word for \"river peninsula\"). The city center is only about a kilometre away. It is the home stadium of German Bundesliga 2 club Werder Bremen.",
            "Westfalenstadion (German pronunciation: [vɛstˈfaːlnˌʃtaːdi̯ɔn]) is a football stadium in Dortmund, North Rhine-Westphalia, Germany, which is the home of Borussia Dortmund. Officially called Signal Iduna Park [zɪɡˌnaːl ʔiˈduːnaː ˌpaʁk] for sponsorship reasons and BVB Stadion Dortmund in UEFA competitions, the name derives from the former Prussian province of Westphalia.\n\nThe stadium is one of the most famous football stadiums in Europe and is renowned for its atmosphere. It has a league capacity of 81,365 (standing and seated) and an international capacity of 65,829 (seated only). It is Germany's largest stadium, the seventh-largest in Europe, and the second-largest home to a top-flight European club after Camp Nou and before the Santiago Bernabéu Stadium. It holds the European record for average fan attendance, set in the 2011–2012 season with almost 1.37 million spectators over 17 games at an average of 80,588 per game. Sales of annual season tickets amounted to 55,000 in 2015.\n\nThe 24,454 capacity Südtribüne (South Bank) is the largest terrace for standing spectators in European football. Famous for the intense atmosphere it breeds, the south terrace has been nicknamed Die Gelbe Wand, meaning \"The Yellow Wall\". The Borusseum, the museum of Borussia Dortmund, is located in the north-east part of the stadium.\n\nThe stadium hosted matches in the 1974 and 2006 FIFA World Cups. It also hosted the 2001 UEFA Cup Final. Various national friendlies and qualification matches for World and European tournaments have been played there as well as matches in European club competitions.",
            "The Waldstadion (German pronunciation: [ˈvalt.ʃtaːdi̯ɔn], English: Forest Stadium), currently known as the Deutsche Bank Park for sponsorship purposes, and formerly known as the Commerzbank-Arena, is a retractable roof sports stadium in Frankfurt, Hesse, Germany. The home stadium of the football club Eintracht Frankfurt, it was opened in 1925. The stadium has been upgraded several times since then; the most recent remodelling was its redevelopment as a football-only stadium in preparation for the 2005 FIFA Confederations Cup and 2006 FIFA World Cup. With a capacity of 51,500 spectators for league matches and 48,500 for American Football and International Football matches, it is among the ten largest football stadiums in Germany. The stadium was one of the nine venues of 2011 FIFA Women's World Cup, and hosted four matches including the final.\n\nThe sports complex, which is owned by the city of Frankfurt, includes the actual stadium and other sports facilities, including a swimming pool, a tennis complex, a beach volleyball court and a winter sports hall. The arena has its own railway station, Frankfurt Stadion, on the national rail network.",
            "Schwarzwald-Stadion is a football stadium in Freiburg, Baden-Württemberg, Germany. It is currently the home of Bundesliga team SC Freiburg. The stadium holds 24,000 spectators and was built in 1953. For many years it was called the Dreisamstadion, situated near the river Dreisam.\n\nIn June 2004 it was given the name of Badenova-Stadion, later Mage Solar Stadion, and for a short time the Stadion an der Schwarzwaldstraße. Due to a sponsorship deal, it is currently named the Schwarzwald-Stadion.\n\nIn 2012, modernising the stadium was deemed unprofitable. In February 2015, a referendum was held to determine whether a new stadium should be built and if so, where. The citizens of Freiburg voted in favour of the construction of a new stadium, SC-Stadion, with a capacity of 34,700 at the Wolfswinkel nearby Freiburg's municipal airport.",
            "Rhein-Neckar-Arena (German pronunciation: [ˌʁaɪnˈnɛkaʁʔaˌʁeːna]), currently known as PreZero Arena and previously as Wirsol Rhein-Neckar-Arena [ˈvɪʁzɔl-] for sponsorship reasons, is a multi-purpose stadium in Sinsheim, Baden-Württemberg, Germany. It is used mostly for football matches and hosts the home matches of 1899 Hoffenheim. The stadium has a capacity of 30,150 people. It replaced TSG 1899 Hoffenheim's former ground, the Dietmar-Hopp-Stadion.\n\nThe stadium is the largest in the Rhine-Neckar metropolitan area, although it is situated in a town with only 36,000 inhabitants.\n\nThe first competitive match was played on 31 January 2009 against FC Energie Cottbus, and ended in a 2–0 win for Hoffenheim. The stadium hosted international matches at the 2011 FIFA Women's World Cup.[4] The Rhein-Neckar-Arena hosted the \"2017 DEL Winter Game\", an outdoor ice hockey game between Adler Mannheim and the Schwenningen Wild Wings on 7 January 2017.",
            "The Müngersdorfer Stadion (German pronunciation: [ˌʁaɪnʔenɛʁˈɡiːˌʃtaːdi̯ɔn];(Now called as RheinEnergieStadion) is a German football stadium in Cologne. It was built on the site of the two previous Müngersdorfer stadiums. It is the home of the local Bundesliga team, 1. FC Köln. The stadium was one of five stadiums hosting both the 2005 FIFA Confederations Cup and 2006 FIFA World Cup, and hosted the 2020 UEFA Europa League Final behind closed doors. Local energy company RheinEnergie AG currently holds the naming rights to the stadium, hence it was known as the Stadion Köln for the final.",
            "Red Bull Arena (German pronunciation: [ʁɛt ˈbʊl ʔaˌʁeːnaː], formerly Zentralstadion [tsɛnˈtʁaːlˌʃtaːdi̯ɔn]), is a football facility located in Leipzig, Saxony, Germany. It is the largest football stadium in the former East Germany and has also hosted music concerts as well as football.\n\nOpened in 2004, it is currently the home stadium for first-division club RB Leipzig, with FC Sachsen Leipzig having previously used the stadium from its opening until 2009. Due to UEFA sponsorship regulations, the stadium is known as the RB Arena for European matches.",
            "Bay Arena (German pronunciation: [ˈbaɪʔaˌʁeːnaː]) is a football stadium in Leverkusen, North Rhine-Westphalia, Germany, which has been the home ground of Bundesliga club Bayer 04 Leverkusen since 1958.",
            "Opel Arena ([ˈoːpl̩ ʔaˌʁeːna]; stylised as OPEL ARENA; also known as the 1. FSV Mainz 05 Arena due to UEFA sponsorship regulations) is a multi-purpose stadium in Mainz, Rhineland-Palatinate, Germany that was opened in July 2011. It is used for football matches, and hosts the home matches of the German Bundesliga side Mainz 05.\n\nThe stadium has a capacity of 34,034 people, of which 19,700 seated, and replaces the Bruchweg stadium, Stadion am Bruchweg. The stadium was originally named Coface Arena ([ˈkoːfas ʔaˌʁeːna]) after a sponsorship deal with COFACE. In July 2016, the stadium arrived at its current name, per a naming rights agreement with Opel.",
            "Borussia-Park (German pronunciation: [boˈʁʊsi̯aːˌpaʁk]; stylised as BORUSSIA-PARK) is a football stadium in Mönchengladbach, North Rhine-Westphalia, Germany which serves as the home stadium of Bundesliga club Borussia Mönchengladbach. It replaced the smaller Bökelbergstadion, which no longer satisfied modern safety standards and international requirements, in July 2004.\n\nBorussia-Park has a capacity of 54,057, of which 16,145 are standing places in the terraces due to popular demand. For international games, the terraces are converted into temporary seating which reduces the stadium's seating capacity to 46,249.\n\nThe new stadium features amenities such as VIP lounges, a fanshop and sports bar, and cost 85 million euro to construct.\n\nDespite its large capacity and relative modernity, the stadium missed out on holding matches during the 2006 World Cup, which Germany hosted. It was the largest capacity Bundesliga stadium not to host World Cup matches, although it did host matches in the 2011 Women's World Cup. It was again not selected as a venue for Germany's first bid as a united nation for the UEFA flagship event EURO 2024.\n\nWith an average occupancy rate of 95.1% it is one of the most frequently visited football stadiums in Europe, placing 13th in 2017 (between Liverpool F.C. and Hamburger SV). This is despite the relatively small size of the city of Mönchengladbach.",
            "Allianz Arena (German: [aˈli̯ants ʔaˌʁeːnaː]; known as Fußball Arena München for UEFA competitions) is a football stadium in Munich, Bavaria, Germany with a 70,000 seating capacity for international matches and 75,000 for domestic matches. Widely known for its exterior of inflated ETFE plastic panels, it is the first stadium in the world with a full colour changing exterior. Located at 25 Werner-Heisenberg-Allee at the northern edge of Munich's Schwabing-Freimann borough on the Fröttmaning Heath, it is the second-largest arena in Germany behind Westfalenstadion in Dortmund.\n\nFC Bayern Munich has played its home games at the Allianz Arena since the start of the 2005–06 season. The club had previously played their home games at the Munich Olympic Stadium since 1972. 1860 Munich previously had a 50% share in the stadium, but Bayern Munich purchased their shares for €11 million in April 2006 due to 1860 Munich suffering from financial issues. The arrangement allowed 1860 Munich to play at the stadium while retaining no ownership until 2025. However, in July 2017 the rental contract was terminated, making Bayern Munich the sole tenants of the stadium.\n\nThe large locally based financial services provider Allianz purchased the naming rights to the stadium for 30 years. However, this name cannot be used when hosting FIFA and UEFA events, since these governing bodies have policies forbidding corporate sponsorship from companies that are not official tournament partners. During the 2006 FIFA World Cup, the stadium was referred to as FIFA WM-Stadion München (FIFA World Cup Stadium, Munich). In UEFA club and Nations League matches, it is known as Fußball Arena München (Football Arena Munich) [ˌfuːsbal ʔaʁeːnaː ˈmʏnçn̩], and it hosted the 2012 UEFA Champions League Final and will host the upcoming 2023 final. The stadium has been nicknamed \"Schlauchboot\" (\"dinghy\"). Since 2012 the museum of Bayern Munich, FC Bayern Erlebniswelt, has been located inside the Allianz Arena.",
            "Arena AufSchalke (German pronunciation: [aˌʁeːna ʔaʊfˈʃalkə]), currently known as Veltins-Arena ([ˈfɛltɪnsʔaˌʁeːna]) for sponsorship reasons, is an indoor football stadium in Gelsenkirchen, North Rhine-Westphalia, Germany. It opened on 13 August 2001, as the new home ground for Bundesliga club FC Schalke 04.\n\nIt hosted the 2004 UEFA Champions League Final and five matches at the 2006 FIFA World Cup, including a quarter-final. It has a capacity of 62,271 (standing and seated) for league matches and 54,740 (seated only) for international matches. The stadium has a retractable roof and a retractable pitch. The naming rights to the stadium were sold on 1 July 2005 to German brewery Veltins.",
            "Mercedes-Benz Arena (German pronunciation: [mɛʁˌtseːdəsˈbɛnts ʔaˌʁeːna]) is a stadium located in Stuttgart, Baden-Württemberg, Germany and home to German Bundesliga club VfB Stuttgart.\n\nBefore 1993 it was called Neckarstadion [ˈnɛkaʁˌʃtaːdi̯ɔn], named after the nearby river Neckar and between 1993 and July 2008 it was called Gottlieb-Daimler-Stadion [ˌɡɔtliːpˈdaɪmlɐˌʃtaːdi̯ɔn]. From the 2008–09 season, the stadium was renamed the Mercedes-Benz Arena, starting with a pre-season friendly against Arsenal on 30 July 2008.",
            "Volkswagen Arena (German pronunciation: [ˈfɔlksvaːɡŋ̍ ʔaˌʁeːnaː]; also known as the VfL Wolfsburg Arena due to UEFA sponsorship regulations) is a football stadium in the German city of Wolfsburg, Lower Saxony. It was opened in 2002 and named after the automotive group Volkswagen AG. The Volkswagen Arena has a capacity of 30,000: 22,000 seats and 8,000 standing places. It is located in the Allerpark and is the home stadium of the football team VfL Wolfsburg.")

    private val stadLocs = arrayOf(
            "Augsburg, Germany",
            "Westend, Charlottenburg-Wilmersdorf, Berlin, Germany",
            "Köpenick, Berlin, Germany",
            "Bielefeld, Germany",
            "Franz-Böhmert-Straße 1, Bremen, Germany",
            "Strobelallee 50 44139 Dortmund, North Rhine-Westphalia, Germany",
            "Frankfurt, Germany",
            "Freiburg, Germany",
            "Sinsheim, Baden-Württemberg, Germany",
            "Aachener Straße 999, Sportpark Müngersdorf, Lindenthal",
            "Am Sportforum 3, Leipzig, Germany",
            "Leverkusen, North Rhine-Westphalia, Germany",
            "Mainz, Rhineland-Palatinate, Germany",
            "Hennes-Weisweiler-Allee 1, Mönchengladbach, North Rhine-Westphalia, Germany",
            "Munich, Germany",
            "Gelsenkirchen, North Rhine-Westphalia, Germany",
            "Stuttgart, Baden-Württemberg, Germany",
            "Wolfsburg, Germany")

    private val stadGeos = arrayOf(
            "geo:48.323139,10.886",
            "geo:52.514722,13.239444",
            "geo:52.457222,13.568056",
            "geo:52.031944,8.516667",
            "geo:53.066394,8.837628",
            "geo:51.492569,7.451842",
            "geo:50.068611,8.645278",
            "geo:47.988889,7.893056",
            "geo:49.238083,8.887611",
            "geo:50.933497,6.874997",
            "geo:51.345794,12.348219",
            "geo:51.038256,7.002206",
            "geo:49.984167,8.224167",
            "geo:51.174583,6.385464",
            "geo:48.218775,11.624753",
            "geo:51.554503,7.067589",
            "geo:48.792269,9.232031",
            "geo:52.432639,10.803889")

    private val stadImgs = intArrayOf(
            R.drawable.club_1_stad,
            R.drawable.club_2_stad,
            R.drawable.club_3_stad,
            R.drawable.club_4_stad,
            R.drawable.club_5_stad,
            R.drawable.club_6_stad,
            R.drawable.club_7_stad,
            R.drawable.club_8_stad,
            R.drawable.club_9_stad,
            R.drawable.club_10_stad,
            R.drawable.club_11_stad,
            R.drawable.club_12_stad,
            R.drawable.club_13_stad,
            R.drawable.club_14_stad,
            R.drawable.club_15_stad,
            R.drawable.club_16_stad,
            R.drawable.club_17_stad,
            R.drawable.club_18_stad)

        private var isPressed = booleanArrayOf(
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false)

    val listData: ArrayList<ClubDetails>
        get() {
            val list = arrayListOf<ClubDetails>()
            for (position in clubNames.indices) {
                val data = ClubDetails()
                data.id = itemId[position]
                data.name = clubNames[position]
                data.desc = clubDescs[position]
                data.logo = clubLogos[position]
                data.stad_name = stadNames[position]
                data.stad_desc = stadDescs[position]
                data.stad_loc = stadLocs[position]
                data.stad_geo = stadGeos[position]
                data.stad_img = stadImgs[position]
                data.stat_pre = isPressed[position]
                list.add(data)
            }
            return list
        }
}